spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: root
    username: postgres
    url: jdbc:postgresql://localhost/orders
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8080

payment-service:
  base-url: http://localhost:8081